version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/backend
    overwrite: true
hooks:
  BeforeInstall:
    - location: /scripts/before-install.sh
      runas: root
  AfterInstall:
    - location: /scripts/after-install.sh
      runas: ubuntu